import 'package:flutter/material.dart';

import '../../../Widgets/textContainer.dart';

class Policy extends StatelessWidget {
  const Policy({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    double width = MediaQuery.of(context).size.width;
    var textStyle =
        TextStyle(fontSize: width * .035, fontWeight: FontWeight.bold);

    return SingleChildScrollView(
        child: Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          "Privacy Policy",
          style: TextStyle(fontSize: width * .05, fontWeight: FontWeight.bold),
        ),
        Text(
          "Last updated: July 14, 2022",
          style: textStyle,
        ),
        const Text(
          "Please read these terms and conditions carefully before using Our Service.",
          textAlign: TextAlign.justify,
        ),
        const SizedBox(height: 8),
        Text(
          "Interpretation and Definitions",
          style: TextStyle(fontWeight: FontWeight.bold, fontSize: width * .043),
        ),
        Text("Interpretation", style: textStyle),
        const Text(
          "The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.",
          textAlign: TextAlign.justify,
        ),
        const SizedBox(height: 8),
        Text(
          'Definitions',
          style: textStyle,
        ),
        const Text("For the purposes of this Privacy Policy:"),
        const TextContainer(
          header: "Account ",
          text:
              "means a unique account created for You to access our Service or parts of our Service.",
        ),
        const TextContainer(
          header: "Company ",
          text:
              "(referred to as either 'the Company', 'We', 'Us' or 'Our' in this Agreement) refers to Sympodium.",
        ),
        const TextContainer(
          header: "Cookies ",
          text:
              "are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.",
        ),
        const TextContainer(
          header: "Country ",
          text: "refers to: Ghana",
        ),
        const TextContainer(
          header: "Device ",
          text:
              "means any device that can access the Service such as a computer, a cellphone or a digital tablet.",
        ),
        const TextContainer(
          header: "Personal Data ",
          text:
              "is any information that relates to an identified or identifiable individual.",
        ),
        const TextContainer(
          header: "Service ",
          text: "refers to the Website.",
        ),
        const TextContainer(
          header: "Service Provider ",
          text:
              "means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.",
        ),
        const TextContainer(
          header: "Usage Data ",
          text:
              " refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).",
        ),
        const TextContainer(
          header: "Website ",
          text:
              "refers to MyDonate, accessible from https://mydonate2.vercel.app/",
        ),
        const TextContainer(
          header: "You ",
          text:
              "means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.",
        ),
        const Text(
          "Collecting and Using Your Personal Data \n"
          "Types of Data Collected\n"
          "Personal Data\n"
          "While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:\n"
          "Email address\n"
          "Usage Data\n"
          "Usage Data is collected automatically when using the Service.",
        ),
        const Text(
          "Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data."
          "When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data."
          "We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.\n"
          "Tracking Technologies and Cookies \n"
          "We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:",
          textAlign: TextAlign.justify,
        ),
        const TextContainer(
          header: "Cookies or Browser Cookies. ",
          text:
              "A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.",
        ),
        const TextContainer(
          header: "Flash Cookies. ",
          text:
              "Certain features of our Service may use local stored objects (or Flash Cookies) to collect and store information about Your preferences or Your activity on our Service. Flash Cookies are not managed by the same browser settings as those used for Browser Cookies. For more information on how You can delete Flash Cookies, please read \"Where can I change the settings for disabling, or deleting local shared objects?\" available at https://helpx.adobe.com/flash-player/kb/disable-local-shared-objects-flash.html#main_Where_can_I_change_the_settings_for_disabling__or_deleting_local_shared_objects_",
        ),
        const TextContainer(
          header: "Web Beacons. ",
          text:
              "Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity)."
              "Cookies can be \"Persistent\" or \"Session\" Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser. You can learn more about cookies on TermsFeed website article.\n"
              "We use both Session and Persistent Cookies for the purposes set out below:",
        ),
        Text(
          "Necessary / Essential Cookies",
          style: textStyle,
        ),
        const Text(
            "Type: Session Cookies \n Administered by: Us \nPurpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services."),
        Text("Cookies Policy / Notice Acceptance Cookies", style: textStyle),
        const Text(
            "Type: Persistent Cookies \n Administered by: Us \nPurpose: These Cookies identify if users have accepted the use of cookies on the Website."),
        Text("Functionality Cookies", style: textStyle),
        const Text("Type: Persistent Cookies \nAdministered by: Us \n"
            "Purpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website."
            "For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy or the Cookies section of our Privacy Policy. \n"
            "Use of Your Personal Data \n"
            "The Company may use Personal Data for the following purposes:")
      ],
    ));
  }
}
